apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-prod-deployment
  namespace: prod
  labels:
    app: medicure-app-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicure-app-prod
  template:
    metadata:
      labels:
        app: medicure-app-prod
    spec:
      containers:
      - name: medicure-app-prod
        image: krishna21290/medicure-app:1.0
        ports:
        - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: medicure-prod-service
  namespace: prod
spec:
  selector:
    app: medicure-app-prod
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8082
    protocol: TCP
    nodePort: 30020
